### ISSUE TITLE
KeyError when optional key config not provided

### ISSUE THREAD

**Issue by pnadolny13** [MeltanoLabs/tap-stackexchange#2]
The readme says that `key` is not required but without it I got a KeyError. So we could either make `key` required and update the doc along with adding a required field in the tap schema or leave it optional and add `.get("key")` instead of '["key"]'.

```
line 55, in get_url_params
    "key": self.config["key"],
```

**Comment by edgarrmondragon** [comment]
@pnadolny13 you're right. Sending in a fix for this to make it truly optional
